services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  backend:
    image: c01_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
